name: Continuous Integration
on:
  workflow_dispatch:
jobs:
  validate:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    services:
      localhost:
        image: ghcr.io/microsoft/documentdb/documentdb-local:latest
        env:
          USERNAME: ciuser
          PASSWORD: cipassword
        ports:
          - 10260:10260
    steps:
      - name: Checkout source
        uses: actions/checkout@v4
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: | 
            10.x
      - name: Install Mongo shell
        run: |
          sudo apt-get install gnupg
          wget -qO- https://www.mongodb.org/static/pgp/server-8.0.asc | sudo tee /etc/apt/trusted.gpg.d/server-8.0.asc
          echo "deb [ arch=amd64,arm64 ] https://repo.mongodb.org/apt/ubuntu noble/mongodb-org/8.0 multiverse" | sudo tee /etc/apt/sources.list.d/mongodb-org-8.0.list
          sudo apt-get update
          sudo apt-get install -y mongodb-mongosh
      - name: Test Mongo shell
        run: |
          mongosh --version
      - name: Run validation script
        working-directory: utilities
        env:
          DOCUMENTDB_IDENTITY: ciuser
          DOCUMENTDB_CREDENTIAL: cipassword
          DOCUMENTDB_HOST: localhost
          DOCUMENTDB_PORT: 10260
        run: |
          dotnet run test.cs --results-directory "tst" --report-trx --report-trx-filename "results.trx" --no-ansi --ignore-exit-code "2"
      - name: Generate CTRF test report
        working-directory: utilities
        run: |
          dotnet run report.cs "tst/results.trx" --output-directory "ctrf" --output-filename "report.json" --test-tool "mstest"
      - name: Upload TRX test results
        uses: actions/upload-artifact@v4
        with:
          name: trx-test-results
          path: 'utilities/**/tst/**/*.trx'
      - name: Upload CTRF test report
        uses: actions/upload-artifact@v4
        with:
          name: ctrf-test-report
          path: 'utilities/**/ctrf/**/*.json'
      - name: Publish CTRF test report
        uses: ctrf-io/github-test-reporter@v1
        with:
          report-path: 'utilities/**/ctrf/**/*.json'
      
      
          
