name: Continuous Deployment
on:
  workflow_dispatch:
  push:
    branches:
      - main
jobs:
  build:
    name: Build Markdown
    runs-on: ubuntu-latest
    permissions:
      contents: read
    environment:
      name: github
      url: https://github.com/documentdb/docs
    steps:
      - name: Checkout source
        uses: actions/checkout@v4
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: | 
            10.x
      - name: Generate Markdown
        working-directory: utilities
        run: |
          dotnet run transform.cs
      - name: Write step summary output
        working-directory: utilities/out
        run: |
          echo "### Generated Markdown content 🚀" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          find . -name '*.md' | sed 's/^/ - /' >> $GITHUB_STEP_SUMMARY
      - name: Upload Markdown content
        uses: actions/upload-artifact@v4
        with:
          name: markdown-content
          path: 'utilities/**/out/**/*.md'